export enum ComponentTypes {
	Race,
	Color,
	Range,
	Select,
	SelectWithColor,
	Clothes,
}

export enum ValuesKeys {
	Race = 'race',
	Gender = 'gender',
	BodyType = 'presetIndexes',
	SkinColor = 'skinColors',
	Weight = 'weights',
	Dirt = 'dirtTints',
	DirtColor = 'dirtColors',
	Scars = 'faceScars',
	NoseType = 'noseTypes',
	NoseHeight = 'noseHeights',
	NoseLength = 'noseLengths',
	JawWidth = 'jawWidths',
	JawHeight = 'jawHeights',
	CheekboneHeight = 'cheekboneHeights',
	CheekboneWidth = 'cheekboneWidths',
	CheekColor = 'cheeksTints',
	UnderNoseColor = 'frownLiness',
	UnderCheekColor = 'cheeksTintLowers',
	NoseColor = 'noseTints',
	ChinColor = 'chinTints',
	NeckColor = 'neckTints',
	ForeheadColor = 'foreHeadTints',
	EyesForm = 'eyesForms',
	EyesColor = 'eyesColors',
	EyesHeight = 'eyesHeigths',
	EyesDistance = 'eyesDistances',
	EyesDeep = 'eyesDepths',
	EyelinerColor = 'eyesLinerColors',
	EyeShadowTopColor = 'eyesUpperShadows',
	EyeShadowBotColor = 'eyesLowerShadows',
	BrowType = 'eyebrowsTypes',
	BrowHeight = 'eyebrowsHeigths',
	BrowWidth = 'eyebrowsWeights',
	BrowDeep = 'eyebrowsForwards',
	LipsForm = 'lipsTypes',
	LipsHeight = 'lipsHeigths',
	LipsDeep = 'lipsForwards',
	ChinWidth = 'chinWeigths',
	ChinLength = 'chinLengths',
	ChinDeep = 'chinForwards',
	LipsColor = 'lipsColors',
	HairStyle = 'hairs',
	BeardStyle = 'facialHairs',
	HairColor = 'hairColors',
	ClothesTop = 'clothesTop',
	ClothesShoes = 'clothesShoes',
}

export const ValueTypes = {
	[ValuesKeys.SkinColor]: ComponentTypes.Color,
	[ValuesKeys.Weight]: ComponentTypes.Range,
	[ValuesKeys.BodyType]: ComponentTypes.Select,

	[ValuesKeys.Dirt]: ComponentTypes.SelectWithColor,
	[ValuesKeys.DirtColor]: ComponentTypes.Color,
	[ValuesKeys.Scars]: ComponentTypes.Select,

	[ValuesKeys.NoseType]: ComponentTypes.Select,
	[ValuesKeys.NoseLength]: ComponentTypes.Range,
	[ValuesKeys.NoseHeight]: ComponentTypes.Range,
	[ValuesKeys.JawWidth]: ComponentTypes.Range,
	[ValuesKeys.JawHeight]: ComponentTypes.Range,
	[ValuesKeys.CheekboneHeight]: ComponentTypes.Range,
	[ValuesKeys.CheekboneWidth]: ComponentTypes.Range,
	[ValuesKeys.CheekColor]: ComponentTypes.Color,
	[ValuesKeys.UnderCheekColor]: ComponentTypes.Color,
	[ValuesKeys.UnderNoseColor]: ComponentTypes.Color,
	[ValuesKeys.NoseColor]: ComponentTypes.Color,
	[ValuesKeys.ChinColor]: ComponentTypes.Color,
	[ValuesKeys.NeckColor]: ComponentTypes.Color,
	[ValuesKeys.ForeheadColor]: ComponentTypes.Color,

	[ValuesKeys.HairStyle]: ComponentTypes.Select,
	[ValuesKeys.BeardStyle]: ComponentTypes.Select,
	[ValuesKeys.HairColor]: ComponentTypes.Color,

	[ValuesKeys.EyesForm]: ComponentTypes.Select,
	[ValuesKeys.EyesColor]: ComponentTypes.Select,
	[ValuesKeys.EyesHeight]: ComponentTypes.Range,
	[ValuesKeys.EyesDistance]: ComponentTypes.Range,
	[ValuesKeys.EyesDeep]: ComponentTypes.Range,
	[ValuesKeys.EyelinerColor]: ComponentTypes.Color,
	[ValuesKeys.EyeShadowTopColor]: ComponentTypes.Color,
	[ValuesKeys.EyeShadowBotColor]: ComponentTypes.Color,

	[ValuesKeys.BrowType]: ComponentTypes.Select,
	[ValuesKeys.BrowHeight]: ComponentTypes.Range,
	[ValuesKeys.BrowWidth]: ComponentTypes.Range,
	[ValuesKeys.BrowDeep]: ComponentTypes.Range,

	[ValuesKeys.LipsForm]: ComponentTypes.Select,
	[ValuesKeys.LipsHeight]: ComponentTypes.Range,
	[ValuesKeys.LipsDeep]: ComponentTypes.Range,
	[ValuesKeys.ChinWidth]: ComponentTypes.Range,
	[ValuesKeys.ChinLength]: ComponentTypes.Range,
	[ValuesKeys.ChinDeep]: ComponentTypes.Range,
	[ValuesKeys.LipsColor]: ComponentTypes.Color,
}

export enum Parts {
	Race = 'race',
	Gender = 'gender',
	Preset = 'Preset',
	Body = 'Body',
	Head = 'Head',
	Face = 'Face',
	Hair = 'Hair',
	Eyes = 'Eyes',
	Eyebrows = 'Eyebrows',
	Mouth = 'Mouth',
	Clothes = 'Clothes',
}

export const BackKeys = {
	presetIndexes: 'presetIndex',
	skinColors: 'skinColor',
	weights: 'weight',
	dirtTints: 'dirtTint',
	dirtColors: 'dirtColor',
	faceScars: 'faceScar',
	noseTypes: 'noseType',
	noseHeights: 'noseHeight',
	noseLengths: 'noseLength',
	jawWidths: 'jawWidth',
	jawHeights: 'jawHeight',
	cheekboneHeights: 'cheekboneHeight',
	cheekboneWidths: 'cheekbondeWidth',
	cheeksTints: 'cheeksTint',
	frownLiness: 'frownLines',
	cheeksTintLowers: 'cheeksTintLower',
	noseTints: 'noseTint',
	chinTints: 'chinTint',
	neckTints: 'neckTint',
	foreHeadTints: 'foreHeadTint',
	eyesForms: 'eyesForm',
	eyesColors: 'eyesColor',
	eyesHeigths: 'eyesHeigth',
	eyesDistances: 'eyesDistance',
	eyesDepths: 'eyesDepth',
	eyesLinerColors: 'eyesLinerColor',
	eyesUpperShadows: 'eyesUpperShadows',
	eyesLowerShadows: 'eyesLowerShadows',
	eyebrowsTypes: 'eyebrowsType',
	eyebrowsHeigths: 'eyebrowsHeigth',
	eyebrowsWeights: 'eyebrowsWeight',
	eyebrowsForwards: 'eyebrowsForward',
	lipsTypes: 'lipsType',
	lipsHeigths: 'lipsHeigth',
	lipsForwards: 'lipsForward',
	chinWeigths: 'chinWeigth',
	chinLengths: 'chinLength',
	chinForwards: 'chinForward',
	lipsColors: 'lipsColor',
	hairs: 'hairs',
	facialHairs: 'facialHair',
	hairColors: 'hairColor',
	clothesTop: 'clothesTop',
	clothesShoes: 'clothesShoes',
}

export const RegExpName: RegExp = /^[А-ЯЁ][а-яё]{2,8}(?: [А-ЯЁ][а-яё]{2,8}){0,2}$/;