import { KeyCodes } from './keyCodes'

export const KeyNames = {
	[KeyCodes.Backspace]: 'Backspace',
	[KeyCodes.Tab]: 'Tab',
	[KeyCodes.Enter]: 'Enter',
	[KeyCodes.LeftShift]: 'Shift',
	[KeyCodes.LeftControl]: 'Ctrl',
	[KeyCodes.LeftAlt]: 'Alt',
	[KeyCodes.Pause]: 'Pause',
	[KeyCodes.CapsLock]: 'CapsLock',
	[KeyCodes.Esc]: 'Esc',
	[KeyCodes.Space]: 'Space',
	[KeyCodes.PageUp]: 'PageUp',
	[KeyCodes.PageDown]: 'PageDown',
	[KeyCodes.End]: 'End',
	[KeyCodes.Home]: 'Home',
	[KeyCodes.ArrowLeft]: 'Arrow Left',
	[KeyCodes.ArrowUp]: 'Arrow Up',
	[KeyCodes.ArrowRight]: 'Arrow Right',
	[KeyCodes.ArrowDown]: 'Arrow Down',
	[KeyCodes.PrintScreen]: 'PrintScreen',
	[KeyCodes.Insert]: 'Insert',
	[KeyCodes.Delete]: 'Delete',
	[KeyCodes.Digit0]: '0',
	[KeyCodes.Digit1]: '1',
	[KeyCodes.Digit2]: '2',
	[KeyCodes.Digit3]: '3',
	[KeyCodes.Digit4]: '4',
	[KeyCodes.Digit5]: '5',
	[KeyCodes.Digit6]: '6',
	[KeyCodes.Digit7]: '7',
	[KeyCodes.Digit8]: '8',
	[KeyCodes.Digit9]: '9',
	[KeyCodes.A]: 'A',
	[KeyCodes.B]: 'B',
	[KeyCodes.C]: 'C',
	[KeyCodes.D]: 'D',
	[KeyCodes.E]: 'E',
	[KeyCodes.F]: 'F',
	[KeyCodes.G]: 'G',
	[KeyCodes.H]: 'H',
	[KeyCodes.I]: 'I',
	[KeyCodes.J]: 'J',
	[KeyCodes.K]: 'K',
	[KeyCodes.L]: 'L',
	[KeyCodes.M]: 'M',
	[KeyCodes.N]: 'N',
	[KeyCodes.O]: 'O',
	[KeyCodes.P]: 'P',
	[KeyCodes.Q]: 'Q',
	[KeyCodes.R]: 'R',
	[KeyCodes.S]: 'S',
	[KeyCodes.T]: 'T',
	[KeyCodes.U]: 'U',
	[KeyCodes.V]: 'V',
	[KeyCodes.W]: 'W',
	[KeyCodes.X]: 'X',
	[KeyCodes.Y]: 'Y',
	[KeyCodes.Z]: 'Z',
	[KeyCodes.Numpad0]: 'Num0',
	[KeyCodes.Numpad1]: 'Num0',
	[KeyCodes.Numpad2]: 'Num2',
	[KeyCodes.Numpad3]: 'Num3',
	[KeyCodes.Numpad4]: 'Num4',
	[KeyCodes.Numpad5]: 'Num5',
	[KeyCodes.Numpad6]: 'Num6',
	[KeyCodes.Numpad7]: 'Num7',
	[KeyCodes.Numpad8]: 'Num8',
	[KeyCodes.Numpad9]: 'Num9',
	[KeyCodes.NumpadMultiply]: 'Num Multiply',
	[KeyCodes.NumpadAdd]: 'Num Plus',
	[KeyCodes.NumpadSubtract]: 'Num Minus',
	[KeyCodes.NumpadDecimal]: 'Num Decimal',
	[KeyCodes.NumpadDivide]: 'Num Divide',
	[KeyCodes.F1]: 'F1',
	[KeyCodes.F2]: 'F2',
	[KeyCodes.F3]: 'F3',
	[KeyCodes.F4]: 'F4',
	[KeyCodes.F5]: 'F5',
	[KeyCodes.F6]: 'F6',
	[KeyCodes.F7]: 'F7',
	[KeyCodes.F8]: 'F8',
	[KeyCodes.F9]: 'F9',
	[KeyCodes.F10]: 'F10',
	[KeyCodes.F11]: 'F11',
	[KeyCodes.F12]: 'F12',
	[KeyCodes.NumLock]: 'NumLock',
	[KeyCodes.ScrollLock]: 'ScrollLock',
	[KeyCodes.Semicolon]: 'Semicolon',
	[KeyCodes.Equal]: 'Equal',
	[KeyCodes.Comma]: 'Comma',
	[KeyCodes.Minus]: 'Minus',
	[KeyCodes.Period]: 'Period',
	[KeyCodes.Slash]: 'Slash',
	[KeyCodes.Backquote]: 'Backquote',
	[KeyCodes.BracketLeft]: 'Bracket Left',
	[KeyCodes.Backslash]: 'Backslash',
	[KeyCodes.BracketRight]: 'Bracket Right',
	[KeyCodes.Quote]: 'Quote',
	[KeyCodes.LeftMouseButton]: 'Mouse Left',
	[KeyCodes.MiddleMouseButton]: 'Mouse Middle',
	[KeyCodes.RightMouseButton]: 'Mouse Right',
	[KeyCodes.MouseButton3]: 'Mouse 3',
	[KeyCodes.MouseButton4]: 'Mouse 4',
	[KeyCodes.MouseButton5]: 'Mouse 5',
	[KeyCodes.MouseButton6]: 'Mouse 6',
	[KeyCodes.MouseButton7]: 'Mouse 7',
}

export const MouseButtonNames = {
	[KeyCodes.LeftMouseButton]: 'Mouse Left',
	[KeyCodes.MiddleMouseButton]: 'Mouse Middle',
	[KeyCodes.RightMouseButton]: 'Mouse Right',
	[KeyCodes.MouseButton3]: 'Mouse 3',
	[KeyCodes.MouseButton4]: 'Mouse 4',
	[KeyCodes.MouseButton5]: 'Mouse 5',
	[KeyCodes.MouseButton6]: 'Mouse 6',
	[KeyCodes.MouseButton7]: 'Mouse 7',
}
