import { KeyCodes } from './keyCodes'
import { MouseButton } from '../types/mouseButton'
import { SkyrimKeyCodes } from '../shared/SkyrimKeyCodes'


export const KeyCodeByDxCode: Record<SkyrimKeyCodes, KeyCodes> = {
	[SkyrimKeyCodes.None]: KeyCodes.Undefined,
	[SkyrimKeyCodes.Escape]: KeyCodes.Esc,
	[SkyrimKeyCodes.N1]: KeyCodes.Digit1,
	[SkyrimKeyCodes.N2]: KeyCodes.Digit2,
	[SkyrimKeyCodes.N3]: KeyCodes.Digit3,
	[SkyrimKeyCodes.N4]: KeyCodes.Digit4,
	[SkyrimKeyCodes.N5]: KeyCodes.Digit5,
	[SkyrimKeyCodes.N6]: KeyCodes.Digit6,
	[SkyrimKeyCodes.N7]: KeyCodes.Digit7,
	[SkyrimKeyCodes.N8]: KeyCodes.Digit8,
	[SkyrimKeyCodes.N9]: KeyCodes.Digit9,
	[SkyrimKeyCodes.N0]: KeyCodes.Digit0,
	[SkyrimKeyCodes.Minus]: KeyCodes.Minus,
	[SkyrimKeyCodes.Equals]: KeyCodes.Equal,
	[SkyrimKeyCodes.Backspace]: KeyCodes.Backspace,
	[SkyrimKeyCodes.Tab]: KeyCodes.Tab,
	[SkyrimKeyCodes.Q]: KeyCodes.Q,
	[SkyrimKeyCodes.W]: KeyCodes.W,
	[SkyrimKeyCodes.E]: KeyCodes.E,
	[SkyrimKeyCodes.R]: KeyCodes.R,
	[SkyrimKeyCodes.T]: KeyCodes.T,
	[SkyrimKeyCodes.Y]: KeyCodes.Y,
	[SkyrimKeyCodes.U]: KeyCodes.U,
	[SkyrimKeyCodes.I]: KeyCodes.I,
	[SkyrimKeyCodes.O]: KeyCodes.O,
	[SkyrimKeyCodes.P]: KeyCodes.P,
	[SkyrimKeyCodes.LeftBracket]: KeyCodes.BracketLeft,
	[SkyrimKeyCodes.RightBracket]: KeyCodes.BracketRight,
	[SkyrimKeyCodes.Enter]: KeyCodes.Enter,
	[SkyrimKeyCodes.LeftControl]: KeyCodes.LeftControl,
	[SkyrimKeyCodes.A]: KeyCodes.A,
	[SkyrimKeyCodes.S]: KeyCodes.S,
	[SkyrimKeyCodes.D]: KeyCodes.D,
	[SkyrimKeyCodes.F]: KeyCodes.F,
	[SkyrimKeyCodes.G]: KeyCodes.G,
	[SkyrimKeyCodes.H]: KeyCodes.H,
	[SkyrimKeyCodes.J]: KeyCodes.J,
	[SkyrimKeyCodes.K]: KeyCodes.K,
	[SkyrimKeyCodes.L]: KeyCodes.L,
	[SkyrimKeyCodes.Semicolon]: KeyCodes.Semicolon,
	[SkyrimKeyCodes.Apostrophe]: KeyCodes.Quote,
	[SkyrimKeyCodes.Console]: KeyCodes.Backquote,
	[SkyrimKeyCodes.LeftShift]: KeyCodes.LeftShift,
	[SkyrimKeyCodes.BackSlash]: KeyCodes.Slash,
	[SkyrimKeyCodes.Z]: KeyCodes.Z,
	[SkyrimKeyCodes.X]: KeyCodes.X,
	[SkyrimKeyCodes.C]: KeyCodes.C,
	[SkyrimKeyCodes.V]: KeyCodes.V,
	[SkyrimKeyCodes.B]: KeyCodes.B,
	[SkyrimKeyCodes.N]: KeyCodes.N,
	[SkyrimKeyCodes.M]: KeyCodes.M,
	[SkyrimKeyCodes.Comma]: KeyCodes.Comma,
	[SkyrimKeyCodes.Period]: KeyCodes.Period,
	[SkyrimKeyCodes.ForwardSlash]: KeyCodes.Slash,
	[SkyrimKeyCodes.RightShift]: KeyCodes.RightShift,
	[SkyrimKeyCodes.NumMult]: KeyCodes.NumpadMultiply,
	[SkyrimKeyCodes.LeftAlt]: KeyCodes.LeftAlt,
	[SkyrimKeyCodes.Spacebar]: KeyCodes.Space,
	[SkyrimKeyCodes.CapsLock]: KeyCodes.CapsLock,
	[SkyrimKeyCodes.F1]: KeyCodes.F1,
	[SkyrimKeyCodes.F2]: KeyCodes.F2,
	[SkyrimKeyCodes.F3]: KeyCodes.F3,
	[SkyrimKeyCodes.F4]: KeyCodes.F4,
	[SkyrimKeyCodes.F5]: KeyCodes.F5,
	[SkyrimKeyCodes.F6]: KeyCodes.F6,
	[SkyrimKeyCodes.F7]: KeyCodes.F7,
	[SkyrimKeyCodes.F8]: KeyCodes.F8,
	[SkyrimKeyCodes.F9]: KeyCodes.F9,
	[SkyrimKeyCodes.F10]: KeyCodes.F10,
	[SkyrimKeyCodes.NumLock]: KeyCodes.NumLock,
	[SkyrimKeyCodes.ScrollLock]: KeyCodes.ScrollLock,
	[SkyrimKeyCodes.Num7]: KeyCodes.Numpad7,
	[SkyrimKeyCodes.Num8]: KeyCodes.Numpad8,
	[SkyrimKeyCodes.Num9]: KeyCodes.Numpad9,
	[SkyrimKeyCodes.NumMinus]: KeyCodes.Minus,
	[SkyrimKeyCodes.Num4]: KeyCodes.Numpad4,
	[SkyrimKeyCodes.Num5]: KeyCodes.Numpad5,
	[SkyrimKeyCodes.Num6]: KeyCodes.Numpad6,
	[SkyrimKeyCodes.NumPlus]: KeyCodes.Equal,
	[SkyrimKeyCodes.Num1]: KeyCodes.Numpad1,
	[SkyrimKeyCodes.Num2]: KeyCodes.Numpad2,
	[SkyrimKeyCodes.Num3]: KeyCodes.Numpad3,
	[SkyrimKeyCodes.Num0]: KeyCodes.Numpad0,
	[SkyrimKeyCodes.NumDot]: KeyCodes.NumpadDecimal,
	[SkyrimKeyCodes.F11]: KeyCodes.F11,
	[SkyrimKeyCodes.F12]: KeyCodes.F12,
	[SkyrimKeyCodes.NumEnter]: KeyCodes.Enter,
	[SkyrimKeyCodes.RightControl]: KeyCodes.RightControl,
	[SkyrimKeyCodes.NumSlash]: KeyCodes.Slash,
	[SkyrimKeyCodes.SysRqPtrScr]: KeyCodes.PrintScreen,
	[SkyrimKeyCodes.RightAlt]: KeyCodes.RightAlt,
	[SkyrimKeyCodes.Pause]: KeyCodes.Pause,
	[SkyrimKeyCodes.Home]: KeyCodes.Home,
	[SkyrimKeyCodes.UpArrow]: KeyCodes.ArrowUp,
	[SkyrimKeyCodes.PgUp]: KeyCodes.PageUp,
	[SkyrimKeyCodes.LeftArrow]: KeyCodes.ArrowLeft,
	[SkyrimKeyCodes.RightArrow]: KeyCodes.ArrowRight,
	[SkyrimKeyCodes.End]: KeyCodes.End,
	[SkyrimKeyCodes.DownArrow]: KeyCodes.ArrowDown,
	[SkyrimKeyCodes.PgDown]: KeyCodes.PageDown,
	[SkyrimKeyCodes.Insert]: KeyCodes.Insert,
	[SkyrimKeyCodes.Delete]: KeyCodes.Delete,
	[SkyrimKeyCodes.LeftMouseButton]: KeyCodes.LeftMouseButton,
	[SkyrimKeyCodes.RightMouseButton]: KeyCodes.RightMouseButton,
	[SkyrimKeyCodes.MiddleMouseButton]: KeyCodes.MiddleMouseButton,
	[SkyrimKeyCodes.MouseButton3]: KeyCodes.MouseButton3,
	[SkyrimKeyCodes.MouseButton4]: KeyCodes.MouseButton4,
	[SkyrimKeyCodes.MouseButton5]: KeyCodes.MouseButton5,
	[SkyrimKeyCodes.MouseButton6]: KeyCodes.MouseButton6,
	[SkyrimKeyCodes.MouseButton7]: KeyCodes.MouseButton7,
	[SkyrimKeyCodes.MouseWheelUp]: KeyCodes.Undefined,
	[SkyrimKeyCodes.MouseWheelDown]: KeyCodes.Undefined,
}

export const KeyCodeByMouseButton: Record<MouseButton, KeyCodes> = {
	[MouseButton.Left]: KeyCodes.LeftMouseButton,
	[MouseButton.Middle]: KeyCodes.MiddleMouseButton,
	[MouseButton.Right]: KeyCodes.RightMouseButton,
	[MouseButton.Additional3]: KeyCodes.MouseButton3,
	[MouseButton.Additional4]: KeyCodes.MouseButton4,
}

const Keys = Object.keys(KeyCodeByDxCode)
const Values = Object.values(KeyCodeByDxCode)

export const getDxCodeByKeyCode = (keyCode: KeyCodes) =>
	Keys[Values.findIndex(el => el === keyCode)]
