import type { PayloadAction } from '@reduxjs/toolkit'
import { createSlice } from '@reduxjs/toolkit'
import { Product } from '../../shared/ArmorStore/Product'
import { CharSlots, ItemType, Quality } from '../../shared/inventory/itemType'

type ArmorStoreState = {
	isOpen: boolean;
	balance: number;
	storeName: string;
	currentProtection: number | null;
	products: Product[];
};

const initialState: ArmorStoreState = {
	isOpen: false,
	balance: 15224,
	storeName: 'Название магазина',
	currentProtection: null,
	products: [
		// {
		// 	id: 'iron_ingot',
		// 	quality: 1,
		// 	image: 'iron_ingot',
		// 	name: 'Железный слиток',
		// 	price: 750,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'leather_strips',
		// 	quality: 1,
		// 	image: 'leather_strips',
		// 	name: 'Полоски кожи',
		// 	price: 300,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'leather',
		// 	quality: 1,
		// 	image: 'leather',
		// 	name: 'Кожа',
		// 	price: 3750,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'steel_ingot',
		// 	quality: 1,
		// 	image: 'steel_ingot',
		// 	name: 'Стальной слиток',
		// 	price: 1050,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'dwarven_metal_ingot',
		// 	quality: 0,
		// 	image: 'dwarven_metal_ingot',
		// 	name: 'Двемерский металлический слиток',
		// 	price: 3750,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'corundum_ingot',
		// 	quality: 0,
		// 	image: 'corundum_ingot',
		// 	name: 'Корундовый слиток',
		// 	price: 3750,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'orichalcum_ingot',
		// 	quality: 0,
		// 	image: 'orichalcum_ingot',
		// 	name: 'Орихалковый слиток',
		// 	price: 3750,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'quicksilver_ingot',
		// 	quality: 2,
		// 	image: 'quicksilver_ingot',
		// 	name: 'Ртутный слиток',
		// 	price: 10500,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'refined_moonstone',
		// 	quality: 2,
		// 	image: 'refined_moonstone',
		// 	name: 'Очищенный лунный камень',
		// 	price: 10500,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'refined_malachite',
		// 	quality: 3,
		// 	image: 'refined_malachite',
		// 	name: 'Очищенный малахит',
		// 	price: 10500,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'ebony_ingot',
		// 	quality: 3,
		// 	image: 'ebony_ingot',
		// 	name: 'Эбонитовый слиток',
		// 	price: 18000,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'dragon_scale',
		// 	quality: 4,
		// 	image: 'dragon_scale',
		// 	name: 'Драконья чешуя',
		// 	price: 45000,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'dragon_bone',
		// 	quality: 4,
		// 	image: 'dragon_bone',
		// 	name: 'Драконья кость',
		// 	price: 45000,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'daedra_heart',
		// 	quality: 4,
		// 	image: 'daedra_heart',
		// 	name: 'Сердца даэдра',
		// 	price: 45000,
		// 	itemType: 'ItemTypeResources',
		// },
		// {
		// 	id: 'iron_sword',
		// 	quality: 1,
		// 	image: 'iron_sword',
		// 	name: 'Железный меч',
		// 	price: 1050,
		// 	damage: 7,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'iron_dagger',
		// 	quality: 1,
		// 	image: 'iron_dagger',
		// 	name: 'Железный кинжал',
		// 	price: 1050,
		// 	damage: 4,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'iron_warhammer',
		// 	quality: 1,
		// 	image: 'iron_warhammer',
		// 	name: 'Железный боевой молот',
		// 	price: 2100,
		// 	damage: 18,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'iron_greatsword',
		// 	quality: 1,
		// 	image: 'iron_greatsword',
		// 	name: 'Железный двуручный меч',
		// 	price: 2100,
		// 	damage: 15,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'steel_dagger',
		// 	quality: 1,
		// 	image: 'steel_dagger',
		// 	name: 'Стальной кинжал',
		// 	price: 2100,
		// 	damage: 5,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'orcish_dagger',
		// 	quality: 0,
		// 	image: 'orcish_dagger',
		// 	name: 'Орочий кинжал',
		// 	price: 5100,
		// 	damage: 6,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dwarven_dagger',
		// 	quality: 0,
		// 	image: 'dwarven_dagger',
		// 	name: 'Двемерский кинжал',
		// 	price: 5100,
		// 	damage: 7,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'elven_dagger',
		// 	quality: 2,
		// 	image: 'elven_dagger',
		// 	name: 'Эльфийский кинжал',
		// 	price: 21300,
		// 	damage: 8,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'glass_dagger',
		// 	quality: 3,
		// 	image: 'glass_dagger',
		// 	name: 'Стеклянный кинжал',
		// 	price: 36300,
		// 	damage: 9,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'ebony_dagger',
		// 	quality: 3,
		// 	image: 'ebony_dagger',
		// 	name: 'Эбонитовый кинжал',
		// 	price: 36300,
		// 	damage: 10,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'daedric_dagger',
		// 	quality: 4,
		// 	image: 'daedric_dagger',
		// 	name: 'Даэдрический кинжал',
		// 	price: 77550,
		// 	damage: 11,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dragonbone_dagger',
		// 	quality: 4,
		// 	image: 'dragonbone_dagger',
		// 	name: 'Кинжал из драконьей кости',
		// 	price: 77550,
		// 	damage: 12,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'steel_sword',
		// 	quality: 1,
		// 	image: 'steel_sword',
		// 	name: 'Стальной меч',
		// 	price: 2100,
		// 	damage: 8,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'orcish_sword',
		// 	quality: 0,
		// 	image: 'orcish_sword',
		// 	name: 'Орочий меч',
		// 	price: 5100,
		// 	damage: 9,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dwarven_sword',
		// 	quality: 0,
		// 	image: 'dwarven_sword',
		// 	name: 'Двемерский меч',
		// 	price: 5100,
		// 	damage: 10,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'elven_sword',
		// 	quality: 2,
		// 	image: 'elven_sword',
		// 	name: 'Эльфийский меч',
		// 	price: 21300,
		// 	damage: 11,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'glass_sword',
		// 	quality: 3,
		// 	image: 'glass_sword',
		// 	name: 'Стеклянный меч',
		// 	price: 36300,
		// 	damage: 12,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'ebony_sword',
		// 	quality: 3,
		// 	image: 'ebony_sword',
		// 	name: 'Эбонитовый меч',
		// 	price: 36300,
		// 	damage: 13,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'daedric_sword',
		// 	quality: 4,
		// 	image: 'daedric_sword',
		// 	name: 'Даэдрический меч',
		// 	price: 77550,
		// 	damage: 14,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dragonbone_sword',
		// 	quality: 4,
		// 	image: 'dragonbone_sword',
		// 	name: 'Даэдрический меч',
		// 	price: 77550,
		// 	damage: 15,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'iron_mace',
		// 	quality: 1,
		// 	image: 'iron_mace',
		// 	name: 'Железная булава',
		// 	price: 1050,
		// 	damage: 9,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'steel_mace',
		// 	quality: 1,
		// 	image: 'steel_mace',
		// 	name: 'Стальная булава',
		// 	price: 2100,
		// 	damage: 10,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'orcish_mace',
		// 	quality: 0,
		// 	image: 'orcish_mace',
		// 	name: 'Орочья булава',
		// 	price: 5100,
		// 	damage: 11,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dwarven_mace',
		// 	quality: 0,
		// 	image: 'dwarven_mace',
		// 	name: 'Двемерская булава',
		// 	price: 5100,
		// 	damage: 12,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'elven_mace',
		// 	quality: 2,
		// 	image: 'elven_mace',
		// 	name: 'Эльфийская булава',
		// 	price: 21300,
		// 	damage: 13,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'glass_mace',
		// 	quality: 3,
		// 	image: 'glass_mace',
		// 	name: 'Стеклянная булава',
		// 	price: 36300,
		// 	damage: 14,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'ebony_mace',
		// 	quality: 3,
		// 	image: 'ebony_mace',
		// 	name: 'Эбонитовая булава',
		// 	price: 36300,
		// 	damage: 15,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'daedric_mace',
		// 	quality: 4,
		// 	image: 'daedric_mace',
		// 	name: 'Даэдрическая булава',
		// 	price: 77550,
		// 	damage: 16,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dragonbone_mace',
		// 	quality: 4,
		// 	image: 'dragonbone_mace',
		// 	name: 'Булава из драконьей кости',
		// 	price: 77550,
		// 	damage: 17,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'iron_war_axe',
		// 	quality: 1,
		// 	image: 'iron_war_axe',
		// 	name: 'Железный топор',
		// 	price: 1050,
		// 	damage: 8,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'steel_war_axe',
		// 	quality: 1,
		// 	image: 'steel_war_axe',
		// 	name: 'Стальной топор',
		// 	price: 2100,
		// 	damage: 9,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'orcish_war_axe',
		// 	quality: 0,
		// 	image: 'orcish_war_axe',
		// 	name: 'Орочий топор',
		// 	price: 5100,
		// 	damage: 10,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dwarven_war_axe',
		// 	quality: 0,
		// 	image: 'dwarven_war_axe',
		// 	name: 'Двемерский топор',
		// 	price: 5100,
		// 	damage: 11,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'elven_war_axe',
		// 	quality: 2,
		// 	image: 'elven_war_axe',
		// 	name: 'Эльфийский топор',
		// 	price: 21300,
		// 	damage: 12,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'glass_war_axe',
		// 	quality: 3,
		// 	image: 'glass_war_axe',
		// 	name: 'Стеклянный топор',
		// 	price: 36300,
		// 	damage: 13,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'ebony_war_axe',
		// 	quality: 3,
		// 	image: 'ebony_war_axe',
		// 	name: 'Эбонитовый топор',
		// 	price: 36300,
		// 	damage: 14,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'daedric_war_axe',
		// 	quality: 4,
		// 	image: 'daedric_war_axe',
		// 	name: 'Даэдрический топор',
		// 	price: 77550,
		// 	damage: 15,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dragonbone_war_axe',
		// 	quality: 4,
		// 	image: 'dragonbone_war_axe',
		// 	name: 'Топор из драконьей кости',
		// 	price: 77550,
		// 	damage: 16,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'steel_greatsword',
		// 	quality: 1,
		// 	image: 'steel_greatsword',
		// 	name: 'Стальной двуручный меч',
		// 	price: 4200,
		// 	damage: 17,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'orcish_greatsword',
		// 	quality: 0,
		// 	image: 'orcish_greatsword',
		// 	name: 'Орочий двуручный меч',
		// 	price: 10200,
		// 	damage: 18,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dwarven_greatsword',
		// 	quality: 0,
		// 	image: 'dwarven_greatsword',
		// 	name: 'Двемерский двуручный меч',
		// 	price: 10200,
		// 	damage: 19,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'elven_greatsword',
		// 	quality: 2,
		// 	image: 'elven_greatsword',
		// 	name: 'Эльфийский двуручный меч',
		// 	price: 42600,
		// 	damage: 20,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'glass_greatsword',
		// 	quality: 3,
		// 	image: 'glass_greatsword',
		// 	name: 'Стеклянный двуручный меч',
		// 	price: 72600,
		// 	damage: 21,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'ebony_greatsword',
		// 	quality: 3,
		// 	image: 'ebony_greatsword',
		// 	name: 'Эбонитовый двуручный меч',
		// 	price: 72600,
		// 	damage: 22,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'daedric_greatsword',
		// 	quality: 4,
		// 	image: 'daedric_greatsword',
		// 	name: 'Даэдрический двуручный меч',
		// 	price: 155100,
		// 	damage: 24,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dragonbone_greatsword',
		// 	quality: 4,
		// 	image: 'dragonbone_greatsword',
		// 	name: 'Двуручный меч из драконьей кости',
		// 	price: 155100,
		// 	damage: 25,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'steel_warhammer',
		// 	quality: 1,
		// 	image: 'steel_warhammer',
		// 	name: 'Стальной боевой молот',
		// 	price: 2100,
		// 	damage: 20,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'orcish_warhammer',
		// 	quality: 0,
		// 	image: 'orcish_warhammer',
		// 	name: 'Орочий боевой молот',
		// 	price: 4200,
		// 	damage: 21,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dwarven_warhammer',
		// 	quality: 0,
		// 	image: 'dwarven_warhammer',
		// 	name: 'Двемерский боевой молот',
		// 	price: 10200,
		// 	damage: 22,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'elven_warhammer',
		// 	quality: 2,
		// 	image: 'elven_warhammer',
		// 	name: 'Эльфийский боевой молот',
		// 	price: 10200,
		// 	damage: 23,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'glass_warhammer',
		// 	quality: 3,
		// 	image: 'glass_warhammer',
		// 	name: 'Стеклянный боевой молот',
		// 	price: 42600,
		// 	damage: 24,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'ebony_warhammer',
		// 	quality: 3,
		// 	image: 'ebony_warhammer',
		// 	name: 'Эбонитовый боевой молот',
		// 	price: 72600,
		// 	damage: 25,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'daedric_warhammer',
		// 	quality: 4,
		// 	image: 'daedric_warhammer',
		// 	name: 'Даэдрический боевой молот',
		// 	price: 72600,
		// 	damage: 27,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dragonbone_warhammer',
		// 	quality: 4,
		// 	image: 'dragonbone_warhammer',
		// 	name: 'Боевой молот из драконьей кости',
		// 	price: 155100,
		// 	damage: 28,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'iron_battleaxe',
		// 	quality: 1,
		// 	image: 'iron_battleaxe',
		// 	name: 'Железная секира',
		// 	price: 2100,
		// 	damage: 16,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'steel_battleaxe',
		// 	quality: 1,
		// 	image: 'steel_battleaxe',
		// 	name: 'Стальная секира',
		// 	price: 4200,
		// 	damage: 18,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'orcish_battleaxe',
		// 	quality: 0,
		// 	image: 'orcish_battleaxe',
		// 	name: 'Орочья секира',
		// 	price: 10200,
		// 	damage: 19,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dwarven_battleaxe',
		// 	quality: 0,
		// 	image: 'dwarven_battleaxe',
		// 	name: 'Двемерская секира',
		// 	price: 10200,
		// 	damage: 20,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'elven_battleaxe',
		// 	quality: 2,
		// 	image: 'elven_battleaxe',
		// 	name: 'Эльфийская секира',
		// 	price: 42600,
		// 	damage: 21,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'glass_battleaxe',
		// 	quality: 3,
		// 	image: 'glass_battleaxe',
		// 	name: 'Стеклянная секира',
		// 	price: 72600,
		// 	damage: 22,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'ebony_battleaxe',
		// 	quality: 3,
		// 	image: 'ebony_battleaxe',
		// 	name: 'Эбонитовая секира',
		// 	price: 72600,
		// 	damage: 23,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'daedric_battleaxe',
		// 	quality: 4,
		// 	image: 'daedric_battleaxe',
		// 	name: 'Даэдрический двуручный меч',
		// 	price: 155100,
		// 	damage: 25,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dragonbone_battleaxe',
		// 	quality: 4,
		// 	image: 'dragonbone_battleaxe',
		// 	name: 'Секира из драконьей кости',
		// 	price: 155100,
		// 	damage: 26,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'long_bow',
		// 	quality: 1,
		// 	image: 'long_bow',
		// 	name: 'Длинный лук',
		// 	price: 2100,
		// 	damage: 12,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'hunting_bow',
		// 	quality: 1,
		// 	image: 'hunting_bow',
		// 	name: 'Охотничий лук',
		// 	price: 4200,
		// 	damage: 14,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'orcish_bow',
		// 	quality: 0,
		// 	image: 'orcish_bow',
		// 	name: 'Орочий лук',
		// 	price: 10200,
		// 	damage: 20,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dwarven_bow',
		// 	quality: 0,
		// 	image: 'dwarven_bow',
		// 	name: 'Двемерский лук',
		// 	price: 10200,
		// 	damage: 24,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'elven_bow',
		// 	quality: 2,
		// 	image: 'elven_bow',
		// 	name: 'Эльфийский лук',
		// 	price: 42600,
		// 	damage: 26,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'glass_bow',
		// 	quality: 3,
		// 	image: 'glass_bow',
		// 	name: 'Стеклянний лук',
		// 	price: 72600,
		// 	damage: 30,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'ebony_bow',
		// 	quality: 3,
		// 	image: 'ebony_bow',
		// 	name: 'Эбонитовый лук',
		// 	price: 72600,
		// 	damage: 34,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'daedric_bow',
		// 	quality: 4,
		// 	image: 'daedric_bow',
		// 	name: 'Даэдрический лук',
		// 	price: 155100,
		// 	damage: 38,
		// 	charSlot: 'CharSlotFirstHand',
		// },
		// {
		// 	id: 'dragonbone_bow',
		// 	quality: 4,
		// 	image: 'dragonbone_bow',
		// 	name: 'Лук из драконьей кости',
		// 	price: 155100,
		// 	damage: 40,
		// 	charSlot: 'CharSlotFirstHand',
		// },
	],
}

export const armorStoreSlice = createSlice({
	name: 'armorStore',
	initialState,
	reducers: {
		show(state) {
			state.isOpen = true
		},
		hide(state) {
			state.isOpen = false
		},

		setCurrentProtection(state, action: PayloadAction<{ value: number }>) {
			state.currentProtection = action.payload.value
		},
		setBalance(state, action: PayloadAction<{ value: number }>) {
			state.balance = action.payload.value
		},
		setStoreName(state, action: PayloadAction<string>) {
			state.storeName = action.payload
		},
		setProducts(state, action: PayloadAction<Product[]>) {
			state.products = action.payload
		},
	},
})

export const armorStoreReducer = armorStoreSlice.reducer
export const armorStoreActions = armorStoreSlice.actions
